import { z } from "zod";

import {
  createTRPCRouter,
  // protectedProcedure,
  publicProcedure,
} from "~/server/api/trpc";

export const productRouter = createTRPCRouter({
  GetProducts: publicProcedure
    .input(z.object({ text: z.string() }))
    .query(({ input }) => {
      return {
        products: [
          {
            id: 1,
            name: "Benang Karet",
            href: "https://cdn.fccindojaya.co.id/products/1.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/1_thumbnail.jpg",
            imageAlt: "Benang Karet",
          },
          {
            id: 2,
            name: "Benang Obras 1/2 Kg",
            href: "https://cdn.fccindojaya.co.id/products/2.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/2_thumbnail.jpg",
            imageAlt: "Benang Obras 1/2 Kg",
          },
          {
            id: 3,
            name: "Benang Jahit Toyolon",
            href: "https://cdn.fccindojaya.co.id/products/3.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/3_thumbnail.jpg",
            imageAlt: "Benang Jahit Toyolon",
          },
          {
            id: 4,
            name: "Diamond 24 Baris",
            href: "https://cdn.fccindojaya.co.id/products/4.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/4_thumbnail.jpg",
            imageAlt: "Diamond 24 Baris",
          },
          {
            id: 5,
            name: "Gantungan Baju Rotan",
            href: "https://cdn.fccindojaya.co.id/products/5.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/5_thumbnail.jpg",
            imageAlt: "Gantungan Baju Rotan",
          },
          {
            id: 6,
            name: "Gantungan Kunci 30 mm",
            href: "https://cdn.fccindojaya.co.id/products/6.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/6_thumbnail.jpg",
            imageAlt: "Gantungan Kunci 30 mm",
          },
          {
            id: 7,
            name: "Gunting Kodok/Kain",
            href: "https://cdn.fccindojaya.co.id/products/7.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/7_thumbnail.jpg",
            imageAlt: "Gunting Kodok/Kain",
          },
          {
            id: 8,
            name: "Hak Jahit",
            href: "https://cdn.fccindojaya.co.id/products/8.png",
            imageSrc: "https://cdn.fccindojaya.co.id/products/8_thumbnail.png",
            imageAlt: "Hak Jahit",
          },
          {
            id: 9,
            name: "Hak Talon",
            href: "https://cdn.fccindojaya.co.id/products/9.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/9_thumbnail.jpg",
            imageAlt: "Hak Talon",
          },
          {
            id: 10,
            name: "Hak Tanam HE/HU",
            href: "https://cdn.fccindojaya.co.id/products/10.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/10_thumbnail.jpg",
            imageAlt: "Hak Tanam HE/HU",
          },
          {
            id: 11,
            name: "Kancing Baby 16L",
            href: "https://cdn.fccindojaya.co.id/products/11.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/11_thumbnail.jpg",
            imageAlt: "Kancing Baby 16L",
          },
          {
            id: 12,
            name: "Kancing Bakar/ATG",
            href: "https://cdn.fccindojaya.co.id/products/12.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/12_thumbnail.jpg",
            imageAlt: "Kancing Bakar/ATG",
          },
          {
            id: 13,
            name: "Kancing Batok",
            href: "https://cdn.fccindojaya.co.id/products/13.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/13_thumbnail.jpg",
            imageAlt: "Kancing Batok",
          },
          {
            id: 14,
            name: "Kancing Bintik A181",
            href: "https://cdn.fccindojaya.co.id/products/14.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/14_thumbnail.jpg",
            imageAlt: "Kancing Bintik A181",
          },
          {
            id: 15,
            name: "Kancing Celana PDL/Jengkol",
            href: "https://cdn.fccindojaya.co.id/products/15.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/15_thumbnail.jpg",
            imageAlt: "Kancing Celana PDL/Jengkol",
          },
          {
            id: 16,
            name: "Kancing Celana/Jas",
            href: "https://cdn.fccindojaya.co.id/products/16.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/16_thumbnail.jpg",
            imageAlt: "Kancing Celana/Jas",
          },
          {
            id: 17,
            name: "Kancing Dinas/PDH 22L",
            href: "https://cdn.fccindojaya.co.id/products/17.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/17_thumbnail.jpg",
            imageAlt: "Kancing Dinas/PDH 22L",
          },
          {
            id: 18,
            name: "Kancing Grafir Classic",
            href: "https://cdn.fccindojaya.co.id/products/18.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/18_thumbnail.jpg",
            imageAlt: "Kancing Grafir Classic",
          },
          {
            id: 19,
            name: "Kancing Grafir Executive",
            href: "https://cdn.fccindojaya.co.id/products/19.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/19_thumbnail.jpg",
            imageAlt: "Kancing Grafir Executive",
          },
          {
            id: 20,
            name: "Kancing Grafir Fashion",
            href: "https://cdn.fccindojaya.co.id/products/20.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/20_thumbnail.jpg",
            imageAlt: "Kancing Grafir Fashion",
          },
          {
            id: 21,
            name: "Kancing Jamur Gepeng UV",
            href: "https://cdn.fccindojaya.co.id/products/21.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/21_thumbnail.jpg",
            imageAlt: "Kancing Jamur Gepeng UV",
          },
          {
            id: 22,
            name: "Kancing Jamur Plastik",
            href: "https://cdn.fccindojaya.co.id/products/22.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/22_thumbnail.jpg",
            imageAlt: "Kancing Jamur Plastik",
          },
          {
            id: 23,
            name: "Kancing Jasko/Epoxy",
            href: "https://cdn.fccindojaya.co.id/products/23.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/23_thumbnail.jpg",
            imageAlt: "Kancing Jasko/Epoxy",
          },
          {
            id: 24,
            name: "Kancing Jeans Goyang",
            href: "https://cdn.fccindojaya.co.id/products/24.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/24_thumbnail.jpg",
            imageAlt: "Kancing Jeans Goyang",
          },
          {
            id: 25,
            name: "Kancing Jeans Ketok",
            href: "https://cdn.fccindojaya.co.id/products/25.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/25_thumbnail.jpg",
            imageAlt: "Kancing Jeans Ketok",
          },
          {
            id: 26,
            name: "Kancing Kemeja 18L",
            href: "https://cdn.fccindojaya.co.id/products/26.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/26_thumbnail.jpg",
            imageAlt: "Kancing Kemeja 18L",
          },
          {
            id: 27,
            name: "Kancing Kemeja 20L",
            href: "https://cdn.fccindojaya.co.id/products/27.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/27_thumbnail.jpg",
            imageAlt: "Kancing Kemeja 20L",
          },
          {
            id: 28,
            name: "Kancing Klepet Plastik",
            href: "https://cdn.fccindojaya.co.id/products/28.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/28_thumbnail.jpg",
            imageAlt: "Kancing Klepet Plastik",
          },
          {
            id: 29,
            name: "Kancing Lingkar Emas/Perak",
            href: "https://cdn.fccindojaya.co.id/products/29.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/29_thumbnail.jpg",
            imageAlt: "Kancing Lingkar Emas/Perak",
          },
          {
            id: 30,
            name: "Kancing Magnet Tas",
            href: "https://cdn.fccindojaya.co.id/products/30.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/30_thumbnail.jpg",
            imageAlt: "Kancing Magnet Tas",
          },
          {
            id: 31,
            name: "Kancing Manohara",
            href: "https://cdn.fccindojaya.co.id/products/31.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/31_thumbnail.jpg",
            imageAlt: "Kancing Manohara",
          },
          {
            id: 32,
            name: "Kancing Mentos",
            href: "https://cdn.fccindojaya.co.id/products/32.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/32_thumbnail.jpg",
            imageAlt: "Kancing Mentos",
          },
          {
            id: 33,
            name: "Kancing Motif Kayu",
            href: "https://cdn.fccindojaya.co.id/products/33.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/33_thumbnail.jpg",
            imageAlt: "Kancing Motif Kayu",
          },
          {
            id: 34,
            name: "Kancing Ripet",
            href: "https://cdn.fccindojaya.co.id/products/34.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/34_thumbnail.jpg",
            imageAlt: "Kancing Ripet",
          },
          {
            id: 35,
            name: "Kancing Root A17",
            href: "https://cdn.fccindojaya.co.id/products/35.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/35_thumbnail.jpg",
            imageAlt: "Kancing Root A17",
          },
          {
            id: 36,
            name: "Kancing Root Coklat/Putih",
            href: "https://cdn.fccindojaya.co.id/products/36.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/36_thumbnail.jpg",
            imageAlt: "Kancing Root Coklat/Putih",
          },
          {
            id: 37,
            name: "Kancing Safari",
            href: "https://cdn.fccindojaya.co.id/products/37.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/37_thumbnail.jpg",
            imageAlt: "Kancing Safari",
          },
          {
            id: 38,
            name: "Kancing Sakura",
            href: "https://cdn.fccindojaya.co.id/products/38.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/38_thumbnail.jpg",
            imageAlt: "Kancing Sakura",
          },
          {
            id: 39,
            name: "Kancing Snap 330/633",
            href: "https://cdn.fccindojaya.co.id/products/39.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/39_thumbnail.jpg",
            imageAlt: "Kancing Snap 330/633",
          },
          {
            id: 40,
            name: "Kancing Snap 7050/201",
            href: "https://cdn.fccindojaya.co.id/products/40.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/40_thumbnail.jpg",
            imageAlt: "Kancing Snap 7050/201",
          },
          {
            id: 41,
            name: "Kancing Snap 7060/8050",
            href: "https://cdn.fccindojaya.co.id/products/41.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/41_thumbnail.jpg",
            imageAlt: "Kancing Snap 7060/8050",
          },
          {
            id: 42,
            name: "Kancing Snap 831",
            href: "https://cdn.fccindojaya.co.id/products/42.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/42_thumbnail.jpg",
            imageAlt: "Kancing Snap 831",
          },
          {
            id: 43,
            name: "Kancing Snap Plastik",
            href: "https://cdn.fccindojaya.co.id/products/43.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/43_thumbnail.jpg",
            imageAlt: "Kancing Snap Plastik",
          },
          {
            id: 44,
            name: "Kancing Zebra",
            href: "https://cdn.fccindojaya.co.id/products/44.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/44_thumbnail.jpg",
            imageAlt: "Kancing Zebra",
          },
          {
            id: 45,
            name: "Karet Elastis Baby 4mm",
            href: "https://cdn.fccindojaya.co.id/products/45.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/45_thumbnail.jpg",
            imageAlt: "Karet Elastis Baby 4mm",
          },
          {
            id: 46,
            name: "Karet Elastis",
            href: "https://cdn.fccindojaya.co.id/products/46.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/46_thumbnail.jpg",
            imageAlt: "Karet Elastis",
          },
          {
            id: 47,
            name: "Karet Elastis Kiloan",
            href: "https://cdn.fccindojaya.co.id/products/47.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/47_thumbnail.jpg",
            imageAlt: "Karet Elastis Kiloan",
          },
          {
            id: 48,
            name: "Karet Papan 7mm",
            href: "https://cdn.fccindojaya.co.id/products/48.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/48_thumbnail.jpg",
            imageAlt: "Karet Papan 7mm",
          },
          {
            id: 49,
            name: "Karet String/Tali Karet",
            href: "https://cdn.fccindojaya.co.id/products/49.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/49_thumbnail.jpg",
            imageAlt: "Karet String/Tali Karet",
          },
          {
            id: 50,
            name: "Kepala Resleting Besi",
            href: "https://cdn.fccindojaya.co.id/products/50.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/50_thumbnail.jpg",
            imageAlt: "Kepala Resleting Besi",
          },
          {
            id: 51,
            name: "Kepala Resleting Plastik",
            href: "https://cdn.fccindojaya.co.id/products/51.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/51_thumbnail.jpg",
            imageAlt: "Kepala Resleting Plastik",
          },
          {
            id: 52,
            name: "Label Size Bordir",
            href: "https://cdn.fccindojaya.co.id/products/52.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/52_thumbnail.jpg",
            imageAlt: "Label Size Bordir",
          },
          {
            id: 53,
            name: "Lem Tembak",
            href: "https://cdn.fccindojaya.co.id/products/53.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/53_thumbnail.jpg",
            imageAlt: "Lem Tembak",
          },
          {
            id: 54,
            name: "Magnet Neodymium",
            href: "https://cdn.fccindojaya.co.id/products/54.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/54_thumbnail.jpg",
            imageAlt: "Magnet Neodymium",
          },
          {
            id: 55,
            name: "Mote Akrilik Susu",
            href: "https://cdn.fccindojaya.co.id/products/55.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/55_thumbnail.jpg",
            imageAlt: "Mote Akrilik Susu",
          },
          {
            id: 56,
            name: "Mote Akrilik Candy",
            href: "https://cdn.fccindojaya.co.id/products/56.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/56_thumbnail.jpg",
            imageAlt: "Mote Akrilik Candy",
          },
          {
            id: 57,
            name: "Mote Akrilik Crystal",
            href: "https://cdn.fccindojaya.co.id/products/57.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/57_thumbnail.jpg",
            imageAlt: "Mote Akrilik Crystal",
          },
          {
            id: 58,
            name: "Mote Akrilik Doff Kilap",
            href: "https://cdn.fccindojaya.co.id/products/58.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/58_thumbnail.jpg",
            imageAlt: "Mote Akrilik Doff Kilap",
          },
          {
            id: 59,
            name: "Mote Akrilik Jelly",
            href: "https://cdn.fccindojaya.co.id/products/59.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/59_thumbnail.jpg",
            imageAlt: "Mote Akrilik Jelly",
          },
          {
            id: 60,
            name: "Mote Akrilik Kilap",
            href: "https://cdn.fccindojaya.co.id/products/60.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/60_thumbnail.jpg",
            imageAlt: "Mote Akrilik Kilap",
          },
          {
            id: 61,
            name: "Mote Renceng",
            href: "https://cdn.fccindojaya.co.id/products/61.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/61_thumbnail.jpg",
            imageAlt: "Mote Renceng",
          },
          {
            id: 62,
            name: "Mutiara Sintetis/Mote Berat",
            href: "https://cdn.fccindojaya.co.id/products/62.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/62_thumbnail.jpg",
            imageAlt: "Mutiara Sintetis/Mote Berat",
          },
          {
            id: 63,
            name: "Payet Akrilik",
            href: "https://cdn.fccindojaya.co.id/products/63.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/63_thumbnail.jpg",
            imageAlt: "Payet Akrilik",
          },
          {
            id: 64,
            name: "Payet Daun Variasi",
            href: "https://cdn.fccindojaya.co.id/products/64.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/64_thumbnail.jpg",
            imageAlt: "Payet Daun Variasi",
          },
          {
            id: 65,
            name: "Payet Mangkok 6 mm",
            href: "https://cdn.fccindojaya.co.id/products/65.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/65_thumbnail.jpg",
            imageAlt: "Payet Mangkok 6 mm",
          },
          {
            id: 66,
            name: "Payet Piring 4 mm",
            href: "https://cdn.fccindojaya.co.id/products/66.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/66_thumbnail.jpg",
            imageAlt: "Payet Piring 4 mm",
          },
          {
            id: 67,
            name: "Payet SQ",
            href: "https://cdn.fccindojaya.co.id/products/67.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/67_thumbnail.jpg",
            imageAlt: "Payet SQ",
          },
          {
            id: 68,
            name: "Peniti Mangkok",
            href: "https://cdn.fccindojaya.co.id/products/68.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/68_thumbnail.jpg",
            imageAlt: "Peniti Mangkok",
          },
          {
            id: 69,
            name: "Piring Plastik",
            href: "https://cdn.fccindojaya.co.id/products/69.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/69_thumbnail.jpg",
            imageAlt: "Piring Plastik",
          },
          {
            id: 70,
            name: "Pita Bendera",
            href: "https://cdn.fccindojaya.co.id/products/70.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/70_thumbnail.jpg",
            imageAlt: "Pita Bendera",
          },
          {
            id: 71,
            name: "Pita Organdi/Kaca",
            href: "https://cdn.fccindojaya.co.id/products/71.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/71_thumbnail.jpg",
            imageAlt: "Pita Organdi/Kaca",
          },
          {
            id: 72,
            name: "Rantai Kuku",
            href: "https://cdn.fccindojaya.co.id/products/72.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/72_thumbnail.jpg",
            imageAlt: "Rantai Kuku",
          },
          {
            id: 73,
            name: "Renda Katun",
            href: "https://cdn.fccindojaya.co.id/products/73.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/73_thumbnail.jpg",
            imageAlt: "Renda Katun",
          },
          {
            id: 74,
            name: "Renda Tile",
            href: "https://cdn.fccindojaya.co.id/products/74.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/74_thumbnail.jpg",
            imageAlt: "Renda Tile",
          },
          {
            id: 75,
            name: "Resleting Aluminium Pendek",
            href: "https://cdn.fccindojaya.co.id/products/75.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/75_thumbnail.jpg",
            imageAlt: "Resleting Aluminium Pendek",
          },
          {
            id: 76,
            name: "Resleting Biasa/Seragam",
            href: "https://cdn.fccindojaya.co.id/products/76.png",
            imageSrc: "https://cdn.fccindojaya.co.id/products/76_thumbnail.png",
            imageAlt: "Resleting Biasa/Seragam",
          },
          {
            id: 77,
            name: "Resleting DBC/Metalon",
            href: "https://cdn.fccindojaya.co.id/products/77.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/77_thumbnail.jpg",
            imageAlt: "Resleting DBC/Metalon",
          },
          {
            id: 78,
            name: "Resleting Jaket Aluminium",
            href: "https://cdn.fccindojaya.co.id/products/78.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/78_thumbnail.jpg",
            imageAlt: "Resleting Jaket Aluminium",
          },
          {
            id: 79,
            name: "Resleting Jaket Coil",
            href: "https://cdn.fccindojaya.co.id/products/79.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/79_thumbnail.jpg",
            imageAlt: "Resleting Jaket Coil",
          },
          {
            id: 80,
            name: "Resleting Jaket Vislon",
            href: "https://cdn.fccindojaya.co.id/products/80.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/80_thumbnail.jpg",
            imageAlt: "Resleting Jaket Vislon",
          },
          {
            id: 81,
            name: "Resleting Jaket Waterproof",
            href: "https://cdn.fccindojaya.co.id/products/81.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/81_thumbnail.jpg",
            imageAlt: "Resleting Jaket Waterproof",
          },
          {
            id: 82,
            name: "Resleting Jeans ATL",
            href: "https://cdn.fccindojaya.co.id/products/82.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/82_thumbnail.jpg",
            imageAlt: "Resleting Jeans ATL",
          },
          {
            id: 83,
            name: "Resleting Jeans PL",
            href: "https://cdn.fccindojaya.co.id/products/83.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/83_thumbnail.jpg",
            imageAlt: "Resleting Jeans PL",
          },
          {
            id: 84,
            name: "Resleting Jepang FCC",
            href: "https://cdn.fccindojaya.co.id/products/84.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/84_thumbnail.jpg",
            imageAlt: "Resleting Jepang FCC",
          },
          {
            id: 85,
            name: "Resleting Jepang SJ Premium",
            href: "https://cdn.fccindojaya.co.id/products/85.png",
            imageSrc: "https://cdn.fccindojaya.co.id/products/85_thumbnail.png",
            imageAlt: "Resleting Jepang SJ Premium",
          },
          {
            id: 86,
            name: "Resleting Rollan Coil",
            href: "https://cdn.fccindojaya.co.id/products/86.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/86_thumbnail.jpg",
            imageAlt: "Resleting Rollan Coil",
          },
          {
            id: 87,
            name: "Resleting Rollan PVC",
            href: "https://cdn.fccindojaya.co.id/products/87.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/87_thumbnail.jpg",
            imageAlt: "Resleting Rollan PVC",
          },
          {
            id: 88,
            name: "Resleting Rollan Waterproof",
            href: "https://cdn.fccindojaya.co.id/products/88.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/88_thumbnail.jpg",
            imageAlt: "Resleting Rollan Waterproof",
          },
          {
            id: 89,
            name: "Resleting Vislon Pendek",
            href: "https://cdn.fccindojaya.co.id/products/89.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/89_thumbnail.jpg",
            imageAlt: "Resleting Vislon Pendek",
          },
          {
            id: 90,
            name: "Resleting Waterproof Pendek",
            href: "https://cdn.fccindojaya.co.id/products/90.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/90_thumbnail.jpg",
            imageAlt: "Resleting Waterproof Pendek",
          },
          {
            id: 91,
            name: "Ring Jojon",
            href: "https://cdn.fccindojaya.co.id/products/91.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/91_thumbnail.jpg",
            imageAlt: "Ring Jojon",
          },
          {
            id: 92,
            name: "Scotlight Kain",
            href: "https://cdn.fccindojaya.co.id/products/92.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/92_thumbnail.jpg",
            imageAlt: "Scotlight Kain",
          },
          {
            id: 93,
            name: "Scotlight Plastik",
            href: "https://cdn.fccindojaya.co.id/products/93.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/93_thumbnail.jpg",
            imageAlt: "Scotlight Plastik",
          },
          {
            id: 94,
            name: "Stopper Tali",
            href: "https://cdn.fccindojaya.co.id/products/94.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/94_thumbnail.jpg",
            imageAlt: "Stopper Tali",
          },
          {
            id: 95,
            name: "Tag Gun",
            href: "https://cdn.fccindojaya.co.id/products/95.png",
            imageSrc: "https://cdn.fccindojaya.co.id/products/95_thumbnail.png",
            imageAlt: "Tag Gun",
          },
          {
            id: 96,
            name: "Tag Pin/Top Pin",
            href: "https://cdn.fccindojaya.co.id/products/96.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/96_thumbnail.jpg",
            imageAlt: "Tag Pin/Top Pin",
          },
          {
            id: 97,
            name: "Tali Hang Tag",
            href: "https://cdn.fccindojaya.co.id/products/97.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/97_thumbnail.jpg",
            imageAlt: "Tali Hang Tag",
          },
          {
            id: 98,
            name: "Tali Hang Tag Plastik",
            href: "https://cdn.fccindojaya.co.id/products/98.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/98_thumbnail.jpg",
            imageAlt: "Tali Hang Tag Plastik",
          },
          {
            id: 99,
            name: "Twill Tape Putih 3 cm",
            href: "https://cdn.fccindojaya.co.id/products/99.jpg",
            imageSrc: "https://cdn.fccindojaya.co.id/products/99_thumbnail.jpg",
            imageAlt: "Twill Tape Putih 3 cm",
          },
          {
            id: 100,
            name: "Velcro/Perekat",
            href: "https://cdn.fccindojaya.co.id/products/100.jpg",
            imageSrc:
              "https://cdn.fccindojaya.co.id/products/100_thumbnail.jpg",
            imageAlt: "Velcro/Perekat",
          },
        ],
      };
    }),
});
