import unittest
from unittest.mock import MagicMock
import binascii
import struct
import os
import csv
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from handlers.deal_get_moldset import deal_get_moldset

class TestDealGetMoldset(unittest.TestCase):
    def setUp(self):
        self.server = MagicMock()
        self.server.data_store = {}
        self.server.moldset_chunks = {}
        self.server.mold_map = None
        self.server.mold_data_buffer = None
        self.server.mold_data_received_len = 0
        
        self.server.sock = MagicMock()
        self.client_addr = ('192.168.1.100', 12345)
        self.entries_in_molddata = [
            "tmClpOpnPress1",
            "tmClpOpnSpeed1",
            "tmClpOpnPosi1",
            "tmClpOpnPress2",
            "tmClpOpnSpeed2",
            "tmClpOpnPosi2",
            "tmClpOpnPress3",
            "tmClpOpnSpeed3",
            "tmClpOpnPosi3",
            "tmClpOpnPress4",
            "tmClpOpnSpeed4",
            "tmClpOpnPosi4",
            "tmClpOpnPress5",
            "tmClpOpnSpeed5",
            "tmClpOpnPosi5",
            "tmClpClsPress1",
            "tmClpClsSpeed1",
            "tmClpClsPosi1",
            "tmClpClsPress2",
            "tmClpClsSpeed2",
            "tmClpClsPosi2",
            "tmClpClsPress3",
            "tmClpClsSpeed3",
            "tmClpClsPosi3",
            "tmClpClsPress4",
            "tmClpClsSpeed4",
            "tmClpClsPosi4",
            "tmClpClsPress5",
            "tmClpClsSpeed5",
            "tmClpClsPosi5",
            "tmInjPress1",
            "tmInjSpeed1",
            "tmInjPosi1",
            "tmInjPress2",
            "tmInjSpeed2",
            "tmInjPosi2",
            "tmInjPress3",
            "tmInjSpeed3",
            "tmInjPosi3",
            "tmInjPress4",
            "tmInjSpeed4",
            "tmInjPosi4",
            "tmInjPress5",
            "tmInjSpeed5",
            "tmInjPosi5",
            "tmInjPress6",
            "tmInjSpeed6",
            "tmInjPosi6",
            "tmInjTime1",
            "tmInjBackPress",
            "tmInjBackSpeed",
            "tmInjBackPosi",
            "tmInjBackDistance",
            "tmInj2HoldMode",
            "tmInj2HoldPres",
            "tmInj2HoldPosn",
            "tmInj2HoldTime",
            "tmInj2HoldModeB",
            "tmInj2HoldPresB",
            "tmInj2HoldPosnB",
            "tmInj2HoldTimeB",
            "tmInjBackPressB",
            "tmInjBackSpeedB",
            "tmInjBackPosiB",
            "tmInjBackDistanceB",
            "tmEjectAdvPress1",
            "tmEjectAdvSpeed1",
            "tmEjectAdvPosi1",
            "tmEjectAdvPress2",
            "tmEjectAdvSpeed2",
            "tmEjectAdvPosi2",
            "tmEjectAdvDelayTime",
            "tmEjectRetPress1",
            "tmEjectRetSpeed1",
            "tmEjectRetPosi1",
            "tmEjectRetPress2",
            "tmEjectRetSpeed2",
            "tmEjectRetPosi2",
            "tmEjectRetDelayTime",
            "tmChargePress1",
            "tmChargeBackPress1",
            "tmChargeSpeed1",
            "tmChargePosi1",
            "tmChargePress2",
            "tmChargeBackPress2",
            "tmChargeSpeed2",
            "tmChargePosi2",
            "tmChargePress3",
            "tmChargeBackPress3",
            "tmChargeSpeed3",
            "tmChargePosi3",
            "tmChargePress4",
            "tmChargeBackPress4",
            "tmChargeSpeed4",
            "tmChargePosi4",
            "tmChargePress5",
            "tmChargeBackPress5",
            "tmChargeSpeed5",
            "tmChargePosi5",
            "tmCoolingBeforeCharge",
            "tmCoreAInPress",
            "tmCoreAInSpeed",
            "tmCoreAInPosi",
            "tmCoreAInTime",
            "tmCoreAOutPress",
            "tmCoreAOutSpeed",
            "tmCoreAOutPosi",
            "tmCoreAOutTime",
            "tmCoreBInPress",
            "tmCoreBInSpeed",
            "tmCoreBInPosi",
            "tmCoreBInTime",
            "tmCoreBOutPress",
            "tmCoreBOutSpeed",
            "tmCoreBOutPosi",
            "tmCoreBOutTime",
            "tmCoreCInPress",
            "tmCoreCInSpeed",
            "tmCoreCInPosi",
            "tmCoreCInTime",
            "tmCoreCOutPress",
            "tmCoreCOutSpeed",
            "tmCoreCOutPosi",
            "tmCoreCOutTime",
            "tmNozzleAdvPress1",
            "tmNozzleAdvSpeed1",
            "tmNozzleAdvPosi1",
            "tmNozzleAdvPress2",
            "tmNozzleAdvSpeed2",
            "tmNozzleAdvPosi2",
            "tmNozzleAdvActTime",
            "tmNozzleRetPress1",
            "tmNozzleRetSpeed1",
            "tmNozzleRetPosi1",
            "tmNozzleRetDelayTime",
            "tmNozzleRetActTime",
            "tmHoldPress1",
            "tmHoldSpeed1",
            "tmHoldTime1",
            "tmHoldPress2",
            "tmHoldSpeed2",
            "tmHoldTime2",
            "tmHoldPress3",
            "tmHoldSpeed3",
            "tmHoldTime3",
            "tmHoldPress4",
            "tmHoldSpeed4",
            "tmHoldTime4",
            "tmHoldPress5",
            "tmHoldSpeed5",
            "tmHoldTime5",
            "tmHoldPress6",
            "tmHoldSpeed6",
            "tmHoldTime6",
            "tmCoolingTime",
            "tmEjectUAdvPress",
            "tmEjectUAdvSpeed",
            "tmEjectUAdvDelayTime",
            "tmEjectURetPress",
            "tmEjectURetSpeed",
            "tmEjectURetDelayTime",
            "tmEjectUAdvCount",
            "tmEjectUAdvTime",
            "tmInjPressB1",
            "tmInjSpeedB1",
            "tmInjPosiB1",
            "tmInjPressB2",
            "tmInjSpeedB2",
            "tmInjPosiB2",
            "tmInjPressB3",
            "tmInjSpeedB3",
            "tmInjPosiB3",
            "tmInjPressB4",
            "tmInjSpeedB4",
            "tmInjPosiB4",
            "tmInjPressB5",
            "tmInjSpeedB5",
            "tmInjPosiB5",
            "tmInjPressB6",
            "tmInjSpeedB6",
            "tmInjPosiB6",
            "tmEjectAdvPressB1",
            "tmEjectAdvSpeedB1",
            "tmEjectAdvPosiB1",
            "tmEjectAdvPressB2",
            "tmEjectAdvSpeedB2",
            "tmEjectAdvPosiB2",
            "tmEjectAdvDelayTimeB",
            "tmEjectRetPressB1",
            "tmEjectRetSpeedB1",
            "tmEjectRetPosiB1",
            "tmEjectRetPressB2",
            "tmEjectRetSpeedB2",
            "tmEjectRetPosiB2",
            "tmEjectRetDelayTimeB",
            "tmChargePressB1",
            "tmChargeBackPressB1",
            "tmChargeSpeedB1",
            "tmChargePosiB1",
            "tmChargePressB2",
            "tmChargeBackPressB2",
            "tmChargeSpeedB2",
            "tmChargePosiB2",
            "tmChargePressB3",
            "tmChargeBackPressB3",
            "tmChargeSpeedB3",
            "tmChargePosiB3",
            "tmChargePressB4",
            "tmChargeBackPressB4",
            "tmChargeSpeedB4",
            "tmChargePosiB4",
            "tmChargePressB5",
            "tmChargeBackPressB5",
            "tmChargeSpeedB5",
            "tmChargePosiB5",
            "tmClpSPMode",
            "tmClpClsPress_C1",
            "tmClpClsSpeed_C1",
            "tmClpClsPosi_C1",
            "tmClpClsPress_C2",
            "tmClpClsSpeed_C2",
            "tmClpClsPosi_C2",
            "tmClpClsPress_C3",
            "tmClpClsSpeed_C3",
            "tmClpClsPosi_C3",
            "tmClpClsLPress_C",
            "tmClpClsLSpeed_C",
            "tmClpClsLPosi_C",
            "tmClpClsHPress_C1",
            "tmClpClsHSpeed_C1",
            "tmClpClsHPosi_C1",
            "tmClpClsHSpeed_C2",
            "tmClpOpnPress_C1",
            "tmClpOpnSpeed_C1",
            "tmClpOpnPosi_C1",
            "tmClpOpnPress_C2",
            "tmClpOpnSpeed_C2",
            "tmClpOpnPosi_C2",
            "tmClpOpnPress_C3",
            "tmClpOpnSpeed_C3",
            "tmClpOpnPosi_C3",
            "tmClpOpnPress_C4",
            "tmClpOpnSpeed_C4",
            "tmClpOpnPosi_C4",
            "tmClpOpnPress_C5",
            "tmClpOpnSpeed_C5",
            "tmClpClsFastPress_S",
            "tmClpClsFastSpeed_S",
            "tmClpClsHoldPress_S",
            "tmClpClsHoldSpeed_S",
            "tmClpClsHoldPosi_S",
            "tmClpClsLockPress_S1",
            "tmClpClsLockSpeed_S1",
            "tmClpClsLockPosi_S1",
            "tmClpClsLockSpeed_S2",
            "tmClpClsLockPosi_S2",
            "tmClpOpnBrokePress_S",
            "tmClpOpnBrokeSpeed_S",
            "tmClpOpnBrokePosi_S",
            "tmClpOpnFastPress_S",
            "tmClpOpnFastSpeed_S",
            "tmClpOpnSlowDownPosi_S",
            "tmCoolingBeforeChargeB",
            "tmCoolingTimeB",
            "tmHoldPressB1",
            "tmHoldSpeedB1",
            "tmHoldTimeB1",
            "tmHoldPressB2",
            "tmHoldSpeedB2",
            "tmHoldTimeB2",
            "tmHoldPressB3",
            "tmHoldSpeedB3",
            "tmHoldTimeB3",
            "tmHoldPressB4",
            "tmHoldSpeedB4",
            "tmHoldTimeB4",
            "tmHoldPressB5",
            "tmHoldSpeedB5",
            "tmHoldTimeB5",
            "tmHoldPressB6",
            "tmHoldSpeedB6",
            "tmHoldTimeB6",
            "tmNozzleAdvPressB1",
            "tmNozzleAdvSpeedB1",
            "tmNozzleAdvPosiB1",
            "tmNozzleAdvPressB2",
            "tmNozzleAdvSpeedB2",
            "tmNozzleAdvPosiB2",
            "tmNozzleAdvActTimeB",
            "tmNozzleRetPressB1",
            "tmNozzleRetSpeedB1",
            "tmNozzleRetPosiB1",
            "tmNozzleRetDelayTimeB",
            "tmNozzleRetActTimeB",
            "tmRotaLocatorAdvPress",
            "tmRotaLocatorAdvSpeed",
            "tmRotaLocatorAdvDelayTime",
            "tmRotaLocatorRetPress",
            "tmRotaLocatorRetSpeed",
            "tmRotaTurnDelayTime",
            "tmRotaCoreAdvPress1",
            "tmRotaCoreAdvSpeed1",
            "tmRotaCoreAdvPosi1",
            "tmRotaCoreAdvDelayTime1",
            "tmRotaCoreAdvPress2",
            "tmRotaCoreAdvSpeed2",
            "tmRotaCoreAdvPosi2",
            "tmRotaCoreRetPress2",
            "tmRotaCoreRetSpeed2",
            "tmRotaCoreRetPosi2",
            "tmRotaCoreRetPress1",
            "tmRotaCoreRetSpeed1",
            "tmRotaCoreRetPosi1",
            "tmRotaCoreRetDelayTime1",
            "tmTemp1_Set",
            "tmTemp2_Set",
            "tmTemp3_Set",
            "tmTemp4_Set",
            "tmTemp5_Set",
            "tmTemp6_Set",
            "tmTemp7_Set",
            "tmTemp8_Set",
            "tmTemp9_Set",
            "tmTemp1_SetB",
            "tmTemp2_SetB",
            "tmTemp3_SetB",
            "tmTemp4_SetB",
            "tmTemp5_SetB",
            "tmTemp6_SetB",
            "tmTemp7_SetB",
            "tmTemp8_SetB",
            "tmTemp9_SetB",
            "tmCycleTimeMax",
            "tmClpClsTimeMax",
            "tmInjTimeMax",
            "tmTurnTimeMax",
            "tmChargeTimeMax",
            "tmClpOpnTimeMax",
            "tmInjBackTimeMax",
            "tmEjectTimeMax",
            "tmClpOpnPosiMax",
            "tmInjStartPosiMax",
            "tmInjEndPosiMax",
            "tmTurnPosiMax",
            "tmTurnPressMax",
            "tmInjMaxPressMax",
            "tmChargeMaxPressMax",
            "tmCycleTimeMin",
            "tmClpClsTimeMin",
            "tmInjTimeMin",
            "tmTurnTimeMin",
            "tmChargeTimeMin",
            "tmClpOpnTimeMin",
            "tmInjBackTimeMin",
            "tmEjectTimeMin",
            "tmClpOpnPosiMin",
            "tmInjStartPosiMin",
            "tmInjEndPosiMin",
            "tmTurnPosiMin",
            "tmTurnPressMin",
            "tmInjMaxPressMin",
            "tmChargeMaxPressMin",
            "tmInjTimeMaxB",
            "tmTurnTimeMaxB",
            "tmChargeTimeMaxB",
            "tmClpOpnTimeMaxB",
            "tmInjBackTimeMaxB",
            "tmEjectTimeMaxB",
            "tmClpOpnPosiMaxB",
            "tmInjStartPosiMaxB",
            "tmInjEndPosiMaxB",
            "tmTurnPosiMaxB",
            "tmTurnPressMaxB",
            "tmInjMaxPressMaxB",
            "tmChargeMaxPressMaxB",
            "tmInjTimeMinB",
            "tmTurnTimeMinB",
            "tmChargeTimeMinB",
            "tmClpOpnTimeMinB",
            "tmInjBackTimeMinB",
            "tmEjectTimeMinB",
            "tmClpOpnPosiMinB",
            "tmInjStartPosiMinB",
            "tmInjEndPosiMinB",
            "tmTurnPosiMinB",
            "tmTurnPressMinB",
            "tmInjMaxPressMinB",
            "tmChargeMaxPressMinB",
            "tmClpMoveOption",
            "tmClpMoveLPress",
            "tmClpMoveLSpeed",
            "tmClpMoveLSPress",
            "tmClpMoveLSSpeed",
            "tmClpMoveRPress",
            "tmClpMoveRSpeed",
            "tmClpMoveRSPress",
            "tmClpMoveRSSpeed",
            "tmLocatorPress",
            "tmLocatorSpeed",
            "tmEjectRAdvPress1",
            "tmEjectRAdvSpeed1",
            "tmEjectRAdvPosi1",
            "tmEjectRAdvPress2",
            "tmEjectRAdvSpeed2",
            "tmEjectRAdvPosiEnd",
            "tmEjectRRetPress1",
            "tmEjectRRetSpeed1",
            "tmEjectRRetPosi1",
            "tmEjectRRetPress2",
            "tmEjectRRetSpeed2",
            "tmEjectRRetPosiEnd",
            "tmEjectUAdvPosi",
            "tmEjectURetPosi",
            "tmEjectURetTime",
            "tmMoldCavity",
        ]

    def _read_hex_from_file(self, filename):
        filepath = os.path.join(os.path.dirname(__file__), 'samples', filename)
        if not os.path.exists(filepath):
            self.fail(f"{filename} not found in handlers/samples/ directory.")
        with open(filepath, 'r') as f:
            return f.read().strip()

    def test_pid_get_moldset_from_csv(self):
        # 1. Run the handler to populate data_store
        hex_data = self._read_hex_from_file('deal_get_moldset.txt')
        data = binascii.unhexlify(hex_data)
        deal_get_moldset(self.server, self.client_addr, data)
        
        # 2. Read Expected CSV
        csv_filename = 'deal_get_moldset_expected.csv'
        csv_path = os.path.join(os.path.dirname(__file__), 'samples', csv_filename)
        
        if not os.path.exists(csv_path):
             self.fail(f"{csv_filename} not found in handlers/samples/")

        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.reader(f)
            next(reader) # Skip header
            
            for row in reader:
                if len(row) < 2:
                    continue
                    
                name = row[0].strip()
                expected_str = row[1].strip()
                
                # Check if data exists in our store
                if name not in self.server.data_store:
                    # Missing values are expected for truncated/sample packets.
                    if expected_str != '0':
                        print('missing', name, expected_str)
                    continue
                
                actual_val = self.server.data_store[name]
                
                try:
                    expected_val = float(expected_str)
                    # Use delta=0.01 for float comparison
                    self.assertAlmostEqual(actual_val, expected_val, delta=0.01, 
                                           msg=f"Mismatch for {name}: expected {expected_val}, got {actual_val}")
                except ValueError:
                    pass

if __name__ == '__main__':
    unittest.main()